// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt1OH6NRp4dSQSPEagNGRhvtuxFtjwXyk',
    appId: '1:214900154341:web:1e7e13e38db6ecb705190c',
    messagingSenderId: '214900154341',
    projectId: 'leccheck-app-db',
    authDomain: 'leccheck-app-db.firebaseapp.com',
    storageBucket: 'leccheck-app-db.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkgtGQ4bAJk7nP8o7kKHRoICt6zDo8Oks',
    appId: '1:214900154341:android:6b5069bbc1a1409805190c',
    messagingSenderId: '214900154341',
    projectId: 'leccheck-app-db',
    storageBucket: 'leccheck-app-db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAODviMSr9ZOUroLWuIJpNUFE5NtNCmV5Q',
    appId: '1:214900154341:ios:33f32bde865e154f05190c',
    messagingSenderId: '214900154341',
    projectId: 'leccheck-app-db',
    storageBucket: 'leccheck-app-db.firebasestorage.app',
    iosClientId: '214900154341-a21bjoq1cedrncvqi6sltnoo9tcath76.apps.googleusercontent.com',
    iosBundleId: 'com.leccheck.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAODviMSr9ZOUroLWuIJpNUFE5NtNCmV5Q',
    appId: '1:214900154341:ios:33f32bde865e154f05190c',
    messagingSenderId: '214900154341',
    projectId: 'leccheck-app-db',
    storageBucket: 'leccheck-app-db.firebasestorage.app',
    iosClientId: '214900154341-a21bjoq1cedrncvqi6sltnoo9tcath76.apps.googleusercontent.com',
    iosBundleId: 'com.leccheck.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCt1OH6NRp4dSQSPEagNGRhvtuxFtjwXyk',
    appId: '1:214900154341:web:1e7e13e38db6ecb705190c',
    messagingSenderId: '214900154341',
    projectId: 'leccheck-app-db',
    authDomain: 'leccheck-app-db.firebaseapp.com',
    storageBucket: 'leccheck-app-db.firebasestorage.app',
  );

  /// Same project as [web]/[windows]; use for Flutter Linux desktop.
  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyCt1OH6NRp4dSQSPEagNGRhvtuxFtjwXyk',
    appId: '1:214900154341:web:1e7e13e38db6ecb705190c',
    messagingSenderId: '214900154341',
    projectId: 'leccheck-app-db',
    authDomain: 'leccheck-app-db.firebaseapp.com',
    storageBucket: 'leccheck-app-db.firebasestorage.app',
  );
}
